/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface TmdbReq {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  query: {
    tmdb_id: number;
  };
}

export interface locationReq {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  body: {
    images?: ({
      description: string;
      id: number;
      main?: boolean;
      type: 1 | 2;
    })[];
    location?: {
      description: string;
      lat: number;
      lng: number;
      movie_id: number;
      title: string;
    };
  };
}

export interface movieGetReq {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  query: {
    id: number;
  };
}
