/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface locationReq {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  images: ({
    description: string;
    id: number;
    main?: boolean;
    type: 1 | 2;
  })[];
  location: {
    description: string;
    movie_id: number;
    position: {
      lat: number;
      lng: number;
    };
    title: string;
  };
}
